services:
  mongodb-primary:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_KEY: ${DATABASE_REPLICA_SET_KEY}
    volumes:
      - 'mongodb_master_data:/bitnami'
    ports:
      - 27017:27017

  mongodb-secondary:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-secondary
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_KEY: ${DATABASE_REPLICA_SET_KEY}

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-arbiter
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_KEY: ${DATABASE_REPLICA_SET_KEY}

volumes:
  mongodb_master_data:
    driver: local