# docker-compose.yml

version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

# version: '3.8'

# services:
#   mongo:
#     image: mongo:latest
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo:/var/lib/mongodb/data
#       - ./data:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: myuser
#       MONGO_INITDB_ROOT_PASSWORD: mypassword

# volumes:
#   mongo: